# Generated by Django 4.2.7 on 2023-12-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detection',
            options={'verbose_name': 'Detection', 'verbose_name_plural': 'Detections'},
        ),
    ]
